"""add new fields for tools

Revision ID: 984881f47ffd
Revises: 0a77ed08a61c
Create Date: 2025-08-29 00:15:20.974771

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "984881f47ffd"
down_revision: Union[str, Sequence[str], None] = "0a77ed08a61c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_thoughts", sa.Column("tool_args", sa.String(), nullable=True))
    op.add_column("agent_thoughts", sa.Column("tool_result", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_thoughts", "tool_result")
    op.drop_column("agent_thoughts", "tool_args")
    # ### end Alembic commands ###
