"""Rename system_prompt to personality_prompt in ai_agents

Revision ID: d65e5582af3f
Revises: 2fca61887ff3
Create Date: 2025-08-28 17:27:39.352181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65e5582af3f'
down_revision: Union[str, Sequence[str], None] = '2fca61887ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('personality_prompt', sa.String(length=5000), nullable=False))
    op.drop_column('ai_agents', 'system_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agents', sa.Column('system_prompt', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.drop_column('ai_agents', 'personality_prompt')
    # ### end Alembic commands ###
